### ISSUE TITLE
About exp/sttts_models

### ISSUE THREAD

**Issue by xxtars** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024#35]
Thank you very much for organizing the challange and publishing the baseline, which has greatly promoted the development of the Voice Privacy field.

I am sorry about that I am not a researcher in Voice Privacy field. However, I recently needed to conduct speaker de-identification for my project, and I was very excited to find your GitHub. I wanted to give it a try. 

I have some problems while running the **sttts** pipeline; I don't know how to find the related files for **asr** and **tts** in configs/anon_sttts.yaml, and I couldn't find the relevant downloads in 01_download_data_model.sh either. Could you provide these files or advise on how I might find them?

Or do you have any other suggestions or works that could better achieve speaker de-identification?

Thank you again, and I look forward to your response.

**Comment by SarinaMeyer** [comment]
Hi, great to hear about your interest in speaker de-identification!
We will upload some information and models of the sttts pipeline soon. We also plan to upload some alternative approaches. Please understand that this will take a couple of days.

**Comment by xxtars** [comment]
Thank you very much for your reply!

**Comment by Bananatos** [comment]
I'm also trying to access the evaluation data from voiceprivacychallenge.univ-avignon.fr after registration and receiving email response but the connection is closed.
I remember the evaluation data was released on 8th March 2024. Did I miss something? 
 ![微信图片_20240319104542](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024/assets/29217325/f6c32591-56fa-41f5-81a1-09334229ba33)

**Comment by pchampio** [comment]
The original issue/question has been fix/answered in the latest version of the Eval plan/code. 
@Bananatos if you are still facing the issue, please open a new issue.
