### ISSUE TITLE
IEMOCAP issue

### ISSUE THREAD

**Issue by alexmplata16** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024#58]
I've installed by my own IEMOCAP and I'm trying to change the path to it in "01_download_data_model.sh" but i don't know exactly in which part do I have to change it. So if someone could help me, it would be  awesome.

**Comment by pchampio** [comment]
Hello,
If your path to IEMOCAP is `/data/IEMOCAP`
```
> ls /data/IEMOCAP
Session1  Session2  Session3  Session4  Session5
```
Then change the first line (line 8) of `./01_download_data_model.sh` file to:
```
iemocap_corpus=/data/IEMOCAP
```
And rerun `./01_download_data_model.sh`.

Please don't hesitate to reopen this issue if any part of the explanation is unclear.

**Comment by alexmplata16** [comment]
I cannot change 01_download_data_model.sh because it says that i don't have permission to it. And as you can see in the image, the clonation appears with that symbol. How can I fix it?
![Captura desde 2024-04-20 21-07-25](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024/assets/159952631/52d6107a-e0f4-4d16-ba6d-7249223b4a24)
