### ISSUE TITLE
Clonation permission issue

### ISSUE THREAD

**Issue by alexmplata16** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024#60]
I cannot change 01_download_data_model.sh because it says that i don't have permission to it. And as you can see in the image, the clonation appears with that symbol. How can I fix it?
![Captura desde 2024-04-20 21-07-25](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024/assets/159952631/a4d1fd11-dff9-41b7-bb0e-2b775e3719ce)

**Comment by pchampio** [comment]
I don't know how you ended up with such permission on the directory after `git clone`.
`chmod/chown` will fix this permission issue, check how to use them online.
I'm also recommending you to follow some introductory Linux/shell courses.
YouTube can help:
https://www.youtube.com/watch?v=LnKoncbQBsM

Closing the issue, linux permission issue from the user side.
