### ISSUE TITLE
Excuting time for Anonymization using phonetic transcriptions and GAN (STTTS): B3

### ISSUE THREAD

**Issue by alexmplata16** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024#62]
I've executed  "./02_run.sh configs/anon_sttts.yaml" 6 days ago and it has been working since that day with no interrumption and it has not finished.

**Comment by pchampio** [comment]
STTTS and NAC are the longest to execute, especially if you are on CPU (which I think is the case in your configuration).
ASRBN-VQ should be faster, but will still take days on CPU.
STTTS, ASRBN-VQ, and NAC largely benefits from a NVIDIA GPU.
mcadams is CPU only.
Evaluation benefits from a NVIDIA GPU too.
I recommend you using a cluster or a computer with a NVIDIA GPU and CUDA installed.
Please re-open this issue if you are indeed using a GPU.
And provide the output of `nvidia-smi`.
