### ISSUE TITLE
CPU only execution fails

### ISSUE THREAD

**Issue by alexmplata16** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024#64]
I've executed the differents annonymization models, and when I execute `exp/results_summary/result_for_rank${anon_data_suffix}` or
`exp/results_summary//result_for_submission${anon_data_suffix}.zip` there's nothing. I mean when i get to `exp/` the folder results_summary doesn't exists.

**Comment by pchampio** [comment]
Hello,
Can you give me the results of `ls ./data` and `ls exp` ?

**Comment by alexmplata16** [comment]
Of course, In the attached image you can see the information you are asking for.
![Captura desde 2024-05-13 10-02-03](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024/assets/159952631/f1ab5da3-1f11-4f2a-b313-4ab4a06ed75a)

**Comment by pchampio** [comment]
The anonymization has been completed for sttts and mcadams it seems like.
However evaluation has not been run.
Please, re-run `02_run.sh` with the stts and mcadams config files, but comment [line 32 of 02_run.sh](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024/blob/main/02_run.sh#L36) to not re-compute the anonymization.
Please provide the logs.

**Comment by alexmplata16** [comment]
Do you mean the one where is written `eval_overwrite="$eval_overwrite \"anon_data_suffix\": \"$anon_suffix\"}"` ??
![image](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024/assets/159952631/7c98077b-b753-4d2a-abcd-ca29602aa783)

**Comment by pchampio** [comment]
Line 36 sorry

**Comment by alexmplata16** [comment]
I've done what you told me and executed .`/02_run.sh configs/anon_mcadams.yaml` and what i got as results were the ones i show you in the image. 
![Captura desde 2024-05-13 13-01-02](https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024/assets/159952631/b8484e86-fc5a-4229-a1be-326a6cc91552)

**Comment by pchampio** [comment]
ASR fails, Do you have a GPU ?

**Comment by alexmplata16** [comment]
No, I don't have a GPU

**Comment by pchampio** [comment]
Sorry, we are expecting you to have a GPU. 

first, because some anonymization pipelines benefit from a cuda accelerator, but more importantly, the evaluation scrips requires training an ASV model.. Which will take too long to execute on CPU.
You can submit a PR if you want to support CPU, but it is not how we intent participants to make use of the tool.
Best
