### ISSUE TITLE
B1 annonimization model

### ISSUE THREAD

**Issue by alexmplata16** [Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024#66]
I've seen that there're scripts to execute B2, B3, B4, B5 and B6 annonimization, but there isn't one for B1. The thing is, how can we compare B1 with all the other models?

**Comment by Natalia-T** [comment]
B1 anonymization is not supported in the current scripts. 
For B1, anonymization scripts from https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022 can be used to obtain anonymized data. 
To perform _utterance-level_  (in contrast to _speaker-level_) anonymization of the enrollment and trial data for B1, the corresponding parameters should be setup in  [https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/blob/master/baseline/config.sh](config.sh): `anon_level_trials=utt` and `anon_level_enroll=utt` (https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2022/blob/d72b50c44677aa9a1ba37b7f0c383c4fde13e05f/baseline/config.sh#L59-L60)

https://github.com/Voice-Privacy-Challenge/Voice-Privacy-Challenge-2024/pull/67/commits/dbd1eeab92eec55dbb9dff2097c5af8c55e45072
